### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by srmnitc** [pyscal/pyscal3#1]
This version enables a major restructure of code. The key ideas behind the restructure of the code base are:
- **Reduce the memory used by pyscal.** Currently atom objects are C++ based. There are always copied for each calculation. The atom objects should be removed, and replaced with a Python object so that it can be directly interacted with. 
- **Reduce C++ code.** To easily maintain the code, C++ side should be reduced to a set of methods for the time critical parts. The rest of the code should be on the python side.

##  Check list for features
- [x] full Atom rewrite (pyscal/pyscal#135 )
- [x] Separate operations into invidual classes (prototype pyscal/pyscal#136 )
- [x] Full system rewrite

### Basic features
- [x] natoms
- [x] concentration
- [x] box
- [x] atoms
- [x] add_atoms
- [x] repeat
- [x] read_file
- [x] to_file
- [x] to_ase
- [x] extract cubic box
- [x] show (#16)
- [x] custom lattice creation (pyscal/pyscal#138)
- [ ] Rotation
- [ ] Slicing
- [x] GBs (#17 )

### Neighbor methods

- [x] Cutoff
- [x] adaptive
- [x] SANN
- [x] Number
- [x] Voronoi (pyscal/pyscal#127 )
- [x] Mask (pyscal/pyscal#118, pyscal/pyscal#119 )
- [x] Filter (pyscal/pyscal#118 )

### Steinhardt

- [x] Normal (pyscal/pyscal#119, pyscal/pyscal#121)
- [x] Averaged (pyscal/pyscal#117, pyscal/pyscal#119, pyscal/pyscal#121)
- [x] Disorder (pyscal/pyscal#122 )

### Solid

- [x] Solid identification (pyscal/pyscal#123 )
- [x] clustering (pyscal/pyscal#123 )
- [x] largest cluster (pyscal/pyscal#123 )

### Misc

- [x] RDF (pyscal/pyscal#124 )
- [x] Angular criteria (pyscal/pyscal#125 )
- [x] Chi params (pyscal/pyscal#125 )
- [x] SRO (#14)
- [x] PMSRO (#14)
- [x] Entropy
- [x] energy
- [x] Diamond neighbors (#4 )
- [x] CNA (#3 )
- [x] Adaptive CNA (#3 )
- [x] Identify diamond neighbors (#4 )
- [x] Centrosymmetry (#5 )
- [x] Vorovector (#13 )
- [x] Space group, point group calculation (pyscal/pyscal#137 )

### Other modules

- [x] Traj process
- [x] crystal structures
- [x] Trajectory (#31)

### Others
- [ ] Update docstrings
- [ ] pyscal/pyscal#22 
- [x] pyscal/pyscal#101 
- [x] pyscal/pyscal#105 
- [x] pyscal/pyscal#108 
- [x] pyscal/pyscal#110 (#30 )
- [x] pyscal/pyscal#111
